ignore:
  - vulnerability: CVE-2025-4516
  - vulnerability: CVE-2025-4947
  - vulnerability: CVE-2025-5025
  - vulnerability: CVE-2025-4802
  - vulnerability: CVE-2025-6069
  - vulnerability: CVE-2025-8058
  - vulnerability: CVE-2025-8194